### PR TITLE
Add new features from https://github.com/ColdTrick/uservalidationbyadmin/issues/2#issuecomment-163242693

### PR DESCRIPTION
**Pull request by Facyla**
Adds : 
- FR translation
- direct email validation (using validation code) + plugin setting
- additional info in admin notification + plugin setting
- additional info in user validation email + plugin setting

### CODE REVIEW

**Comment by Facyla** [comment]
Geolocation was not added yet, but supporting function was also added in this PR.

Reason is it requires to store the registration IP, or should only be used when using immediate notification, as it depends on server remote IP global var.

**Comment by Facyla** [comment]
Found a better geolocation provider (up to 10k free queries per hour), so now implemented the guessed geolocation feature.
As we do not have the registration IP information in cron, also store the registration IP temporarly : it is removed when the user account is enabled.

**Comment by Facyla** [comment]
Corrected typo in language files

**Comment by jdalsem** [comment]
this went stale... most features are now part of core

**Pull request closed without merging**
